breakfastData = [
    {"name": "Scrambled Eggs", "calories": 140, "url": "https://i.ibb.co/f8tkTmB/Scrambled-Eggs-5-SQ.webp"},
    {"name": "Omelette (with veggies)", "calories": 250, "url": "https://i.ibb.co/B37Lp7f/Cheesy-Vegetable-Omelette-Featured-Image.jpg"},
    {"name": "Greek Yogurt with Berries", "calories": 150, "url": "https://i.ibb.co/s1ps7zc/Greek-Yogurt-Berry-Parfaits-1.jpg"},
    {"name": "Toast with Peanut Butter", "calories": 300, "url": "https://i.ibb.co/Qf8NW1Y/RR180.jpg"},
    {"name": "Breakfast Burrito", "calories": 500, "url": "https://i.ibb.co/dmrfbCW/breakfast-burrito-recipe-16.jpg"},
    {"name": "Avocado Toast", "calories": 350, "url":"https://i.ibb.co/0tj2gfb/avocado-toast1.jpg"},
    {"name": "Bagel with Cream Cheese", "calories": 450, "url": "https://i.ibb.co/Px7Pmyz/Keto-Parmesan-Everything-Bagel-Square-0001.jpg"},
    {"name": "Pancakes with Syrup", "calories": 520, "url": "https://i.ibb.co/8g7wBWG/pancake-syrup-1500-10.jpg"},
    {"name": "Waffles with Fruit and Whipped Cream", "calories": 610, "url": "https://i.ibb.co/SwjxwPR/3-A658-C27-577-C-4-D47-B516-DBAD41-B35-D69-scaled.jpg"},
    {"name": "Smoothie Bowl (with fruit and granola)", "calories": 400, "url": "https://i.ibb.co/T4nTFD1/k-archive-2a28d8d3b128d1e3305998496b7bca4970993db7.jpg"},
    {"name": "Fruit Salad", "calories": 120, "url": "https://i.ibb.co/87vxzMc/2289556-0981629410f0446d9bec11f0a9ece43c.jpg"},
    {"name": "Bacon, Egg, and Cheese Sandwich", "calories": 500, "url": "https://i.ibb.co/QX6LVJn/bacon-egg-cheese-recipe-snippet.jpg"},
    {"name": "Sausage and Biscuits", "calories": 600, "url": "https://i.ibb.co/x5RJvff/large-cheddar-biscuits-smoked-sausage.jpg"},
    {"name": "Hash Browns", "calories": 250, "url": "https://i.ibb.co/2KfkWd0/Hash-browns.webp"},
    {"name": "Cereal (with milk)", "calories": 300, "url": "https://i.ibb.co/jhwbZ25/attachment-engin-akyurt-h-Gsq0a-OZM-w-unsplash.jpg"},
    {"name": "Muffin (blueberry)", "calories": 400, "url": "https://i.ibb.co/NLzLQPB/blueberry-muffins-fb-ig-7-scaled.webp"},
    {"name": "Breakfast Quiche (with spinach and feta)", "calories": 350, "url": "https://i.ibb.co/Km7NS2L/Easy-Crustless-Quiche-with-Spinach-and-Feta-9.jpg"},
    {"name": "Breakfast Tacos (with scrambled eggs, chorizo, and salsa)", "calories": 400, "url": "https://i.ibb.co/nzypySc/bkfsttacos.webp"},
    {"name": "Huevos Rancheros", "calories": 450, "url": "https://i.ibb.co/tpZXjBW/Huevos-Rancheros-06.jpg"},
    {"name": "Croissant with Jam", "calories": 300, "url": "https://i.ibb.co/sHVh5rX/50448771982-6d6c6c8057-b.jpg"},
    {"name": "Breakfast Sandwich (with turkey, egg, and cheese)", "calories": 400, "url": "https://i.ibb.co/PG0BGnV/image-recipe-monte-cristo-turkey-breakfast-sandwich.jpg"},
    {"name": "Frittata (with vegetables)", "calories": 250, "url": "https://i.ibb.co/B6QPzpn/MR-Vegetable-Fritatta177.jpg"},
    {"name": "English Muffin with Peanut Butter and Banana", "calories": 350, "url": "https://i.ibb.co/xGNCySw/5327207-d1469e8a7eb745b48c5b78abc4ce9ee4.jpg"}
]


lunchData = [
    {"name": "Grilled Chicken Salad", "calories": 400, "url": "https://i.ibb.co/pztxXk1/Grilled-Chicken-Salad-Recipe-Square.jpg"},
    {"name": "Turkey and Cheese Sandwich", "calories": 350, "url": "https://i.ibb.co/z5XMbSb/Grilled-Turkey-and-Cheese-Sandwich-OG-scaled.jpg"},
    {"name": "Vegetable Soup", "calories": 200, "url": "https://i.ibb.co/SBmM4Dm/easy-crock-pot-vegetable-soup-2-5.jpg"},
    {"name": "Caesar Salad (with chicken)", "calories": 450, "url": "https://i.ibb.co/ZVfMKYp/instagram-In-Stream-Square-Low-carb-Caesar-salad-4.jpg"},
    {"name": "Pasta Salad (with veggies)", "calories": 300, "url": "https://i.ibb.co/xhrCd3s/Easy-Vegetable-Pasta-Salad-SQUARE.webp"},
    {"name": "Black Bean Burger", "calories": 350, "url": "https://i.ibb.co/gmHjnGJ/BFV8045-Black-Bean-Burgers-Thumb1080-B.jpg"},
    {"name": "Hummus and Veggie Wrap", "calories": 400, "url": "https://i.ibb.co/NKhVvw8/Hummus-Veggie-Wrap-Up-EXPS-CWAS18-106657-B04-05-4b.jpg"},
    {"name": "Quinoa Bowl (with roasted vegetables)", "calories": 450, "url": "https://i.ibb.co/KbbXmCc/quinoa-roasted-veggies-5-scaled.jpg"},
    {"name": "Taco Salad", "calories": 500, "url": "https://i.ibb.co/m6YpxX6/taco-salad-13.jpg"},
    {"name": "Tomato Soup (with grilled cheese)", "calories": 600, "url": "https://i.ibb.co/6tkKLgr/grilled-cheese-and-tomato-soup-5.jpg"},
    {"name": "Vegetarian Chili", "calories": 350, "url": "https://i.ibb.co/cFSsRmt/k-archive-9fff417ed363c61374bb3a2523683b9949b51fb9.jpg"},
    {"name": "BLT Sandwich", "calories": 450, "url": "https://i.ibb.co/4Vy6mBb/How-to-make-the-best-BLT-recipe-4-scaled.jpg"},
    {"name": "Chicken Fajitas", "calories": 550, "url": "https://i.ibb.co/RD7VWMZ/chicken-fajitas-recipe-square.jpg"},
    {"name": "Beef Stir-Fry (with veggies)", "calories": 400, "url": "https://i.ibb.co/WcqGnDP/Beef-and-Vegetable-Stir-Fry-16.jpg"},
    {"name": "Mediterranean Salad (with feta and olives)", "calories": 350, "url": "https://i.ibb.co/4212XpZ/the-perfect-greek-salad-7.jpg"},
    {"name": "Baked Potato (with broccoli and cheese)", "calories": 300, "url": "https://i.ibb.co/5YyNScd/Baked-Potato-with-Cheese-Sauce-39.webp"},
    {"name": "Falafel Wrap", "calories": 450, "url": "https://i.ibb.co/kBKzDD2/62708678.jpg"},
    {"name": "Vegetable Stir-Fry (with tofu)", "calories": 350, "url": "https://i.ibb.co/BfMp3yz/Tofu-Stir-Fry-Thumbnail.jpg"},
    {"name": "Chicken and Broccoli Alfredo", "calories": 600, "url": "https://i.ibb.co/K5W13Rq/Best-Chicken-Broccoli-Alfredo-Recipe-720x720.jpg"},
    {"name": "Egg Salad Sandwich", "calories": 400, "url": "https://i.ibb.co/QYVGdV1/Classic-Egg-Salad-featurex.jpg"},
    {"name": "Tuna Salad (with crackers)", "calories": 350, "url": "https://i.ibb.co/TgZjcmB/Tuna-Salad-Recipe-3.jpg"},
    {"name": "Pizza (with veggies)", "calories": 500, "url": "https://i.ibb.co/3hSqXZC/veggie-pizza-featured-image-3.png"},
    {"name": "Shrimp and Vegetable Skewers", "calories": 400, "url": "https://i.ibb.co/92CWFyT/Lemon-Garlic-Butter-Shrimp-1.jpg"},
    {"name": "Grilled Cheese Sandwich (with tomato soup)", "calories": 600, "url": "https://i.ibb.co/pdtSwjk/Tomato-soup-with-grilled-cheese-5.jpg"}
]

dinnerData = [
    {"name": "Grilled Salmon (with vegetables)", "calories": 500, "url": "https://i.ibb.co/S0L3qdR/5544320-04f567e988ce416dadc24ba38716147d.jpg"},
    {"name": "Spaghetti and Meatballs", "calories": 600, "url": "https://i.ibb.co/RyKbLk6/21353-italian-spaghetti-sauce-with-meatballs-3x2-138-1ce49b508a6e483ca909431025e8240d.jpg"},
    {"name": "Chicken Teriyaki (with rice)", "calories": 550, "url": "https://i.ibb.co/9HS1wss/teriyaki-chicken-bowl-donburi-the-heirloom-pantry-03.jpg"},
    {"name": "Beef Tacos (with salsa and guacamole)", "calories": 450, "url": "https://i.ibb.co/GpjYngw/beef-tacos-with-guacamole-528766.jpg"},
    {"name": "Baked Chicken (with sweet potato)", "calories": 400, "url": "https://i.ibb.co/L8vjnbT/mr-chicken-23-2000.jpg"},
    {"name": "Shrimp Scampi (with pasta)", "calories": 550, "url": "https://i.ibb.co/ZKRwVJp/2021-09-30-greek-shrimp-scampi-1.jpg"},
    {"name": "Vegetable Stir-Fry (with chicken)", "calories": 450, "url": "https://i.ibb.co/GfDsPGj/chicken-stir-fry-1.jpg"},
    {"name": "Pesto Pasta (with roasted vegetables)", "calories": 500, "url": "https://i.ibb.co/FBDZY9K/2017-11-05-garlic-roasted-vegetable-pesto-pasta-0.jpg"},
    {"name": "Beef and Broccoli (with rice)", "calories": 450, "url": "https://i.ibb.co/vck6ptW/beef-with-broccoli-4.jpg"},
    {"name": "Grilled Chicken (with quinoa)", "calories": 400, "url": "https://i.ibb.co/fkPDn9n/14189115575-d43c0fd926-o.jpg"},
    {"name": "Salmon Cakes (with mixed vegetables)", "calories": 400, "url": "https://i.ibb.co/KXxV5WL/Baked-Salmon-Cakes-Stacked.jpg"},
    {"name": "Stuffed Peppers (with ground turkey)", "calories": 350, "url": "https://i.ibb.co/r64Zn0C/79805-Stuffed-Peppers-Withturkey-And-Vegtables-MFS-2x3-0048.jpg"},
    {"name": "Chickpea Curry (with naan bread)", "calories": 400, "url": "https://i.ibb.co/4RNq8Sk/chickpea-spinach-curry-over-rice.jpg"},
    {"name": "Pork Chops (with roasted vegetables)", "calories": 500, "url": "https://i.ibb.co/g9yNG7B/pork-chops-with-maple-roasted-vegetables-1980x1320-124503-1.jpg"},
    {"name": "Cauliflower Fried Rice (with shrimp)", "calories": 400, "url": "https://i.ibb.co/qg15qdV/cauliflower-shrimp-fried-rice.jpg"},
    {"name": "Tomato and Basil Pizza", "calories": 600, "url": "https://i.ibb.co/VW7RvfL/margherita-pizza.jpg"},
    {"name": "Baked Cod (with vegetables)", "calories": 450, "url": "https://i.ibb.co/rxXG56w/Best-Baked-Cod-with-Lemon.jpg"},
    {"name": "Vegetable Lasagna", "calories": 400, "url": "https://i.ibb.co/jfzqnpQ/easy-vegetable-lasagna-primavera-sq-037.jpg"},
    {"name": "Beef Stroganoff (with egg noodles)", "calories": 550, "url": "https://i.ibb.co/1ZNdB7y/25202beef-stroganoff-iii-ddmfs-3x4-233-X-139857e2c80e4e54b48bdcecf43cab58.jpg"},
    {"name": "Mushroom Risotto", "calories": 450, "url": "https://i.ibb.co/JnVtgZ3/Creamy-Mushroom-Risotto-0-4-X5.jpg"},
    {"name": "Spinach and Feta Stuffed Chicken", "calories": 400, "url": "https://i.ibb.co/k0rGdDh/spinach-and-feta-cheese-stuffed-chi-8.jpg"},
    {"name": "Vegetable Fajitas (with beans and rice)", "calories": 450, "url": "https://i.ibb.co/G0FQ5sL/loaded-vegetable-fajita-rice-bowls-3.jpg"},
    {"name": "Meatball Sub (with marinara sauce)", "calories": 550, "url": "https://i.ibb.co/gzCfg7r/meatball-sub-recipe-08.jpg"},
    {"name": "Honey Mustard Glazed Salmon (with roasted vegetables)", "calories": 500, "url": "https://i.ibb.co/yn504jd/Sheet-Pan-Honey-Mustard-Glazed-Salmon-Roasted-Vegetables.jpg"}
]

snackData = [
    {"name": "Apple slices with almond butter", "calories": 200, "url": "https://i.ibb.co/d2DmsNb/3759286-ca9f503b9884484ebdf15c6edf1b124c.jpg"},
    {"name": "Greek yogurt with berries and honey", "calories": 150, "url": "https://i.ibb.co/0mSK33B/eatingrichly.jpg"},
    {"name": "Trail mix (nuts, seeds, and dried fruit)", "calories": 200, "url": "https://i.ibb.co/9bVPjF1/July-05-2018-DSC-2593.jpg"},
    {"name": "Hummus and baby carrots", "calories": 150, "url": "https://i.ibb.co/qgcZs84/1117-carrots-goat-cheese-hummus.webp"},
    {"name": "Roasted chickpeas", "calories": 150, "url": "https://i.ibb.co/D4Pw6k1/Roasted-Chickpeas-005.webp"},
    {"name": "Edamame", "calories": 100, "url": "https://i.ibb.co/XLMPwGG/Sesame-Spiced-Edamame-0-4-X5-500x500.jpg"},
    {"name": "Turkey and cheese roll-ups", "calories": 200, "url": "https://i.ibb.co/t2GnRs5/cheesy-turkey-roll-ups-1x1-zz-220922.jpg"},
    {"name": "Cottage cheese with pineapple", "calories": 150, "url": "https://i.ibb.co/C0Q8Gv6/Pineapple-and-cottage-cheese-Bowl.jpg"},
    {"name": "Protein shake (with fruit and almond milk)", "calories": 200, "url": "https://i.ibb.co/10qVmvH/paleo-banana-almond-butter-smoothie-1.jpg"},
    {"name": "Popcorn (air-popped)", "calories": 100, "url": "https://i.ibb.co/sChdwxT/popcorn-528376765.jpg"},
    {"name": "Hard-boiled egg", "calories": 70, "url": "https://i.ibb.co/wwNtH8t/how-to-hard-boil-eggs-2.jpg"},
    {"name": "Celery sticks with peanut butter", "calories": 200, "url": "https://i.ibb.co/gW44vV5/6ded4d792e79419883b5caa448cf92a9.jpg"},
    {"name": "Tuna salad (on whole grain crackers)", "calories": 200, "url": "https://i.ibb.co/cXsVGf8/Tuna-Salad-Recipe-3-1.jpg"},
    {"name": "String cheese", "calories": 80, "url": "https://i.ibb.co/WKgCg6T/string-cheese.jpg"},
    {"name": "Dark chocolate (70percent cocoa)", "calories": 150, "url": "https://i.ibb.co/23fK4Bn/should-you-eat-dark-chocolate-its-up-to-you-but-here-are-the-facts-3.jpg"},
    {"name": "Pistachios (shelled)", "calories": 170, "url": "https://i.ibb.co/6Hh2FjM/shelled-pistachios-dry-roasted-salted-177.jpg"},
    {"name": "Fruit smoothie (with protein powder)", "calories": 200, "url": "https://i.ibb.co/864b3M0/freshly-blended-fruit-smoothies-of-various-colors-royalty-free-image-537522498-1544458651.jpg"},
    {"name": "Rice cakes with avocado and tomato", "calories": 150, "url": "https://i.ibb.co/2kztKSp/rice-cakes-picture.jpg"},
    {"name": "Baked sweet potato chips", "calories": 150, "url": "https://i.ibb.co/5YcfCVj/baked-sweet-potato-chips-recipe-7-of-7.jpg"},
    {"name": "Almonds (raw)", "calories": 160, "url": "https://i.ibb.co/hcD2rVB/raw-almonds.png"},
    {"name": "Energy balls (oats, nuts, and dried fruit)", "calories": 200, "url": "https://i.ibb.co/JdXv4v2/Superfood-Energy-Balls-11.jpg"},
    {"name": "Low-fat cheese and whole grain crackers", "calories": 200, "url": "https://i.ibb.co/r0stcXY/cheese-crackers-additives-worse-than-hfcs.jpg"},
    {"name": "Sliced bell pepper with hummus", "calories": 150, "url": "https://i.ibb.co/YW5wBh6/Mediterranean-Hummus-Stuffed-Peppers2.jpg"},
    {"name": "Rice crackers with guacamole", "calories": 200, "url": "https://i.ibb.co/z4mLbXH/Rice-cake-with-avocado-and-cream-cheese.jpg"}
]

mealsData = [
    {"name": "Oatmeal with Banana and Almonds", "calories": 350},
    {"name": "Scrambled Eggs with Avocado Toast", "calories": 400},
    {"name": "Smoothie Bowl with Berries and Granola", "calories": 300},
    {"name": "Greek Yogurt with Honey and Walnuts", "calories": 250},
    {"name": "Chicken Caesar Salad", "calories": 500},
    {"name": "Turkey and Cheese Sandwich", "calories": 450},
    {"name": "Grilled Salmon with Quinoa and Roasted Vegetables", "calories": 700},
    {"name": "Pesto Pasta with Chicken and Broccoli", "calories": 800},
    {"name": "Vegetarian Chili with Cornbread", "calories": 600},
    {"name": "Hummus with Carrots and Whole Wheat Pita", "calories": 150},
    {"name": "Apple with Peanut Butter", "calories": 200},
    {"name": "Greek Yogurt with Berries", "calories": 100},
    {"name": "Hard-Boiled Egg with Whole Wheat Crackers", "calories": 150},
    {"name": "Cheese and Crackers", "calories": 250},
    {"name": "Trail Mix", "calories": 150},
    {"name": "Baked Chicken Breast with Brown Rice and Steamed Vegetables", "calories": 600},
    {"name": "Beef Stir-Fry with Mixed Vegetables and Rice Noodles", "calories": 800},
    {"name": "Grilled Portobello Mushroom Burger with Sweet Potato Fries", "calories": 650},
    {"name": "Vegetable Frittata with Whole Wheat Toast", "calories": 400},
    {"name": "Whole Wheat Pizza with Veggies and Chicken", "calories": 700},
    {"name": "Tofu and Vegetable Curry with Brown Rice", "calories": 500},
    {"name": "Shrimp and Broccoli Stir-Fry with Rice Noodles", "calories": 550},
    {"name": "Black Bean Soup with Whole Wheat Bread", "calories": 400},
    {"name": "Vegetable Stir-Fry with Tofu and Brown Rice", "calories": 600},
    {"name": "Grilled Chicken Caesar Wrap", "calories": 450},
    {"name": "Salmon and Avocado Sushi Roll", "calories": 400},
    {"name": "Roast Beef and Swiss Sandwich with Tomato Soup", "calories": 700},
    {"name": "Quinoa and Black Bean Salad with Avocado Dressing", "calories": 400},
    {"name": "Pork and Vegetable Kebabs with Couscous", "calories": 600}
]
