breakfastData = [
    {"name": "Scrambled Eggs", "calories": 140, "url": "https://i.ibb.co/f8tkTmB/Scrambled-Eggs-5-SQ.webp"},
    {"name": "Omelette (with veggies)", "calories": 250, "url": "https://i.ibb.co/B37Lp7f/Cheesy-Vegetable-Omelette-Featured-Image.jpg"},
    {"name": "Greek Yogurt with Berries", "calories": 150, "url": "https://i.ibb.co/s1ps7zc/Greek-Yogurt-Berry-Parfaits-1.jpg"},
    {"name": "Toast with Peanut Butter", "calories": 300, "url": "https://i.ibb.co/Qf8NW1Y/RR180.jpg"},
    {"name": "Breakfast Burrito", "calories": 500, "url": "https://i.ibb.co/dmrfbCW/breakfast-burrito-recipe-16.jpg"},
    {"name": "Avocado Toast", "calories": 350, "url":"https://i.ibb.co/0tj2gfb/avocado-toast1.jpg"},
    {"name": "Bagel with Cream Cheese", "calories": 450, "url": "https://i.ibb.co/Px7Pmyz/Keto-Parmesan-Everything-Bagel-Square-0001.jpg"},
    {"name": "Pancakes with Syrup", "calories": 520, "url": "https://i.ibb.co/8g7wBWG/pancake-syrup-1500-10.jpg"},
    {"name": "Waffles with Fruit and Whipped Cream", "calories": 610, "url": "https://i.ibb.co/SwjxwPR/3-A658-C27-577-C-4-D47-B516-DBAD41-B35-D69-scaled.jpg"},
    {"name": "Smoothie Bowl (with fruit and granola)", "calories": 400, "url": "https://i.ibb.co/T4nTFD1/k-archive-2a28d8d3b128d1e3305998496b7bca4970993db7.jpg"},
    {"name": "Fruit Salad", "calories": 120, "url": "https://i.ibb.co/87vxzMc/2289556-0981629410f0446d9bec11f0a9ece43c.jpg"},
    {"name": "Bacon, Egg, and Cheese Sandwich", "calories": 500, "url": "https://i.ibb.co/QX6LVJn/bacon-egg-cheese-recipe-snippet.jpg"},
    {"name": "Sausage and Biscuits", "calories": 600, "url": "https://i.ibb.co/x5RJvff/large-cheddar-biscuits-smoked-sausage.jpg"},
    {"name": "Hash Browns", "calories": 250, "url": "https://i.ibb.co/2KfkWd0/Hash-browns.webp"},
    {"name": "Cereal (with milk)", "calories": 300, "url": "https://i.ibb.co/jhwbZ25/attachment-engin-akyurt-h-Gsq0a-OZM-w-unsplash.jpg"},
    {"name": "Muffin (blueberry)", "calories": 400, "url": "https://i.ibb.co/NLzLQPB/blueberry-muffins-fb-ig-7-scaled.webp"},
    {"name": "Breakfast Quiche (with spinach and feta)", "calories": 350, "url": "https://i.ibb.co/Km7NS2L/Easy-Crustless-Quiche-with-Spinach-and-Feta-9.jpg"},
    {"name": "Breakfast Tacos (with scrambled eggs, chorizo, and salsa)", "calories": 400, "url": "https://i.ibb.co/nzypySc/bkfsttacos.webp"},
    {"name": "Huevos Rancheros", "calories": 450, "url": "https://i.ibb.co/tpZXjBW/Huevos-Rancheros-06.jpg"},
    {"name": "Croissant with Jam", "calories": 300, "url": "https://i.ibb.co/sHVh5rX/50448771982-6d6c6c8057-b.jpg"},
    {"name": "Breakfast Sandwich (with turkey, egg, and cheese)", "calories": 400, "url": "https://i.ibb.co/PG0BGnV/image-recipe-monte-cristo-turkey-breakfast-sandwich.jpg"},
    {"name": "Frittata (with vegetables)", "calories": 250, "url": "https://i.ibb.co/B6QPzpn/MR-Vegetable-Fritatta177.jpg"},
    {"name": "English Muffin with Peanut Butter and Banana", "calories": 350, "url": "https://i.ibb.co/xGNCySw/5327207-d1469e8a7eb745b48c5b78abc4ce9ee4.jpg"}
]


lunchData = [
    {"name": "Grilled Chicken Salad", "calories": 400},
    {"name": "Turkey and Cheese Sandwich", "calories": 350},
    {"name": "Vegetable Soup", "calories": 200},
    {"name": "Caesar Salad (with chicken)", "calories": 450},
    {"name": "Pasta Salad (with veggies)", "calories": 300},
    {"name": "Black Bean Burger", "calories": 350},
    {"name": "Hummus and Veggie Wrap", "calories": 400},
    {"name": "Quinoa Bowl (with roasted vegetables)", "calories": 450},
    {"name": "Taco Salad", "calories": 500},
    {"name": "Tomato Soup (with grilled cheese)", "calories": 600},
    {"name": "Vegetarian Chili", "calories": 350},
    {"name": "BLT Sandwich", "calories": 450},
    {"name": "Chicken Fajitas", "calories": 550},
    {"name": "Beef Stir-Fry (with veggies)", "calories": 400},
    {"name": "Mediterranean Salad (with feta and olives)", "calories": 350},
    {"name": "Baked Potato (with broccoli and cheese)", "calories": 300},
    {"name": "Falafel Wrap", "calories": 450},
    {"name": "Vegetable Stir-Fry (with tofu)", "calories": 350},
    {"name": "Chicken and Broccoli Alfredo", "calories": 600},
    {"name": "Egg Salad Sandwich", "calories": 400},
    {"name": "Tuna Salad (with crackers)", "calories": 350},
    {"name": "Pizza (with veggies)", "calories": 500},
    {"name": "Shrimp and Vegetable Skewers", "calories": 400},
    {"name": "Grilled Cheese Sandwich (with tomato soup)", "calories": 600}
]

dinnerData = [
    {"name": "Grilled Salmon (with vegetables)", "calories": 500},
    {"name": "Spaghetti and Meatballs", "calories": 600},
    {"name": "Chicken Teriyaki (with rice)", "calories": 550},
    {"name": "Beef Tacos (with salsa and guacamole)", "calories": 450},
    {"name": "Baked Chicken (with sweet potato)", "calories": 400},
    {"name": "Shrimp Scampi (with pasta)", "calories": 550},
    {"name": "Vegetable Stir-Fry (with chicken)", "calories": 450},
    {"name": "Pesto Pasta (with roasted vegetables)", "calories": 500},
    {"name": "Beef and Broccoli (with rice)", "calories": 450},
    {"name": "Grilled Chicken (with quinoa)", "calories": 400},
    {"name": "Salmon Cakes (with mixed vegetables)", "calories": 400},
    {"name": "Stuffed Peppers (with ground turkey)", "calories": 350},
    {"name": "Chickpea Curry (with naan bread)", "calories": 400},
    {"name": "Pork Chops (with roasted vegetables)", "calories": 500},
    {"name": "Cauliflower Fried Rice (with shrimp)", "calories": 400},
    {"name": "Tomato and Basil Pizza", "calories": 600},
    {"name": "Baked Cod (with vegetables)", "calories": 450},
    {"name": "Vegetable Lasagna", "calories": 400},
    {"name": "Beef Stroganoff (with egg noodles)", "calories": 550},
    {"name": "Mushroom Risotto", "calories": 450},
    {"name": "Spinach and Feta Stuffed Chicken", "calories": 400},
    {"name": "Vegetable Fajitas (with beans and rice)", "calories": 450},
    {"name": "Meatball Sub (with marinara sauce)", "calories": 550},
    {"name": "Honey Mustard Glazed Salmon (with roasted vegetables)", "calories": 500}
]

snackData = [
    {"name": "Apple slices with almond butter", "calories": 200},
    {"name": "Greek yogurt with berries and honey", "calories": 150},
    {"name": "Trail mix (nuts, seeds, and dried fruit)", "calories": 200},
    {"name": "Hummus and baby carrots", "calories": 150},
    {"name": "Roasted chickpeas", "calories": 150},
    {"name": "Edamame", "calories": 100},
    {"name": "Turkey and cheese roll-ups", "calories": 200},
    {"name": "Cottage cheese with pineapple", "calories": 150},
    {"name": "Protein shake (with fruit and almond milk)", "calories": 200},
    {"name": "Popcorn (air-popped)", "calories": 100},
    {"name": "Hard-boiled egg", "calories": 70},
    {"name": "Celery sticks with peanut butter", "calories": 200},
    {"name": "Tuna salad (on whole grain crackers)", "calories": 200},
    {"name": "String cheese", "calories": 80},
    {"name": "Dark chocolate (70percent cocoa)", "calories": 150},
    {"name": "Pistachios (shelled)", "calories": 170},
    {"name": "Fruit smoothie (with protein powder)", "calories": 200},
    {"name": "Rice cakes with avocado and tomato", "calories": 150},
    {"name": "Baked sweet potato chips", "calories": 150},
    {"name": "Almonds (raw)", "calories": 160},
    {"name": "Energy balls (oats, nuts, and dried fruit)", "calories": 200},
    {"name": "Low-fat cheese and whole grain crackers", "calories": 200},
    {"name": "Sliced bell pepper with hummus", "calories": 150},
    {"name": "Rice crackers with guacamole", "calories": 200}
]

mealsData = [
    {"name": "Oatmeal with Banana and Almonds", "calories": 350},
    {"name": "Scrambled Eggs with Avocado Toast", "calories": 400},
    {"name": "Smoothie Bowl with Berries and Granola", "calories": 300},
    {"name": "Greek Yogurt with Honey and Walnuts", "calories": 250},
    {"name": "Chicken Caesar Salad", "calories": 500},
    {"name": "Turkey and Cheese Sandwich", "calories": 450},
    {"name": "Grilled Salmon with Quinoa and Roasted Vegetables", "calories": 700},
    {"name": "Pesto Pasta with Chicken and Broccoli", "calories": 800},
    {"name": "Vegetarian Chili with Cornbread", "calories": 600},
    {"name": "Hummus with Carrots and Whole Wheat Pita", "calories": 150},
    {"name": "Apple with Peanut Butter", "calories": 200},
    {"name": "Greek Yogurt with Berries", "calories": 100},
    {"name": "Hard-Boiled Egg with Whole Wheat Crackers", "calories": 150},
    {"name": "Cheese and Crackers", "calories": 250},
    {"name": "Trail Mix", "calories": 150},
    {"name": "Baked Chicken Breast with Brown Rice and Steamed Vegetables", "calories": 600},
    {"name": "Beef Stir-Fry with Mixed Vegetables and Rice Noodles", "calories": 800},
    {"name": "Grilled Portobello Mushroom Burger with Sweet Potato Fries", "calories": 650},
    {"name": "Vegetable Frittata with Whole Wheat Toast", "calories": 400},
    {"name": "Whole Wheat Pizza with Veggies and Chicken", "calories": 700},
    {"name": "Tofu and Vegetable Curry with Brown Rice", "calories": 500},
    {"name": "Shrimp and Broccoli Stir-Fry with Rice Noodles", "calories": 550},
    {"name": "Black Bean Soup with Whole Wheat Bread", "calories": 400},
    {"name": "Vegetable Stir-Fry with Tofu and Brown Rice", "calories": 600},
    {"name": "Grilled Chicken Caesar Wrap", "calories": 450},
    {"name": "Salmon and Avocado Sushi Roll", "calories": 400},
    {"name": "Roast Beef and Swiss Sandwich with Tomato Soup", "calories": 700},
    {"name": "Quinoa and Black Bean Salad with Avocado Dressing", "calories": 400},
    {"name": "Pork and Vegetable Kebabs with Couscous", "calories": 600}
]
